services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    env_file:
      - .env
    volumes:
      - ./data:${N8N_USER_FOLDER:-/home/node/.n8n}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network

networks:
  app_network:
    external: true
    name: ${APP_COMPOSE_PROJECT_NAME:-rps-rps_dev}_rps_network
