map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

server {
  listen 127.0.0.1:8786;
  server_name appli.laroche360.ca;

  server_name_in_redirect off;
  port_in_redirect off;
  absolute_redirect off;
  client_max_body_size 20m;

  set_real_ip_from 127.0.0.1;
  real_ip_header X-Forwarded-For;

  add_header X-Content-Type-Options "nosniff" always;
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header Referrer-Policy "strict-origin-when-cross-origin" always;

  location /.well-known/acme-challenge/ {
    root /var/www/html;
    default_type text/plain;
    allow all;
  }

  location / {
    proxy_pass http://127.0.0.1:8787;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_read_timeout 3600;
    proxy_send_timeout 3600;
  }

  access_log /var/log/nginx/rps_app_access.log;
  error_log /var/log/nginx/rps_app_error.log warn;
}

server {
  listen 127.0.0.1:8786;
  server_name automation.laroche360.ca;

  server_name_in_redirect off;
  port_in_redirect off;
  absolute_redirect off;
  client_max_body_size 20m;

  set_real_ip_from 127.0.0.1;
  real_ip_header X-Forwarded-For;

  add_header X-Content-Type-Options "nosniff" always;
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header Referrer-Policy "strict-origin-when-cross-origin" always;

  location /.well-known/acme-challenge/ {
    root /var/www/html;
    default_type text/plain;
    allow all;
  }

  location / {
    proxy_pass http://127.0.0.1:8787;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_read_timeout 3600;
    proxy_send_timeout 3600;
  }

  access_log /var/log/nginx/rps_n8n_access.log;
  error_log /var/log/nginx/rps_n8n_error.log warn;
}
